name: Increment MY_SECRET on Every Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Get current secret value
        id: get-secret
        run: |
          CURRENT_VALUE=$(gh secret list --repo "sanjay0661/gp2-project-new" --visibility all | grep MY_SECRET || echo "")
          if [ -z "$CURRENT_VALUE" ]; then
            echo "MY_SECRET=1" >> $GITHUB_ENV
          else
            VALUE=$(gh secret list --repo "sanjay0661/gp2-project-new" --visibility all | grep MY_SECRET | awk '{print $2}')
            NEW_VALUE=$((VALUE + 1))
            echo "MY_SECRET=$NEW_VALUE" >> $GITHUB_ENV
          fi
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}

      - name: Update secret with new value
        run: |
          gh secret set MY_SECRET \
            --body "${MY_SECRET}" \
            --repo "sanjay0661/gp2-project-new"
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          MY_SECRET: ${{ env.MY_SECRET }}
