name: Increment Variable on Every Run

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-variable:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Get current variable value
        id: get-var
        run: |
          CURRENT_VALUE=$(gh variable get MY_SECRET --repo "sanjay0661/gp2-project-new" --json value -q .value || echo "")
          if [ -z "$CURRENT_VALUE" ]; then
            NEW_VALUE=1
          else
            NEW_VALUE=$((CURRENT_VALUE + 1))
          fi
          echo "NEW_VALUE=$NEW_VALUE" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}

      - name: Update variable with new value
        run: |
          gh variable set MY_SECRET \
            --body "${NEW_VALUE}" \
            --repo "sanjay0661/gp2-project-new"
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
          NEW_VALUE: ${{ env.NEW_VALUE }}
