name: Update Secret on Every Run

on:
  push:
    branches:
      - main   # run automatically on push to main
  workflow_dispatch:  # still allow manual trigger too

jobs:
  update-secret:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Generate new secret value
        run: |
          echo "SECRET_VALUE=$(date +%s | sha256sum | cut -c1-32)" >> $GITHUB_ENV

      - name: Update GitHub Secret
        run: |
          gh secret set MY_SECRET \
            --body "$SECRET_VALUE" \
            --repo "sanjay0661/gp2-project-new"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
