name: Update Secret on Every Run

on:
  workflow_dispatch:

jobs:
  update-secret:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # needed for checkout
      actions: write       # needed for updating secrets
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate new secret value
        id: generate
        run: |
          echo "SECRET_VALUE=$(date +%s | sha256sum | cut -c1-32)" >> $GITHUB_ENV

      - name: Update GitHub Secret
        run: |
          gh secret set MY_SECRET --body "$SECRET_VALUE"
        env:
          GH_TOKEN: ${{ secrets.TEST_GITHUB_TOKEN }}
